/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobme.pk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Devakumar
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        combobox();
        combobox1();
        combobox2();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECT CLASS YEAR AND DEPARTMENT ");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("YEAR");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CLASS");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPARTMENT");

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("View Timetable");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "8:50-9:40", "9:50-10:40", "11:00-11:50", "12:00-12:50", "2:00-2:50", "3:00-3:50"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_Id", "Course_Name", "Faculty_Name"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Details");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(291, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void combobox(){
         try{
            //sql connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from department";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to combobox              
               String dept =rs.getString("dept_name");
               jComboBox4.addItem(dept);                 
           }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
        private void combobox1(){
         try{
            //sql connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select distinct year from student";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to combobox              
               String yr =rs.getString("year");
               jComboBox5.addItem(yr);                 
           }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
        private void combobox2(){
         try{
            //sql connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select distinct class_id from class";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to combobox              
               String cl =rs.getString("class_id");
               jComboBox1.addItem(cl);                 
           }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        try{
            if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("CSE")){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
        }
            else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("CSE")){
                    Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
            else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("CSE")){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
            else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("CSE")){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
            else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("CSE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable2";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
            else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("CSE")){
                Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable2";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
            else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("CSE")){
                Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable3";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
            else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("CSE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable3";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
             else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("ECE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period2");
               String Period_2 = rs.getString("period1");
               String Period_3 = rs.getString("period4");
               String Period_4 = rs.getString("period3");
               String Period_5 = rs.getString("period6");
               String Period_6 = rs.getString("period5");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
             else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("ECE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
              else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("ECE")){
                Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable4";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
             else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("ECE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable4";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
               else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("ECE")){
                Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable5";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
             else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("ECE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable5";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
                  else if(jComboBox1.getSelectedItem().equals("A") && jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("ECE")){
                Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable6";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
           }
            con.close();
            }
             else if(jComboBox1.getSelectedItem().equals("B") && jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("ECE")){
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable6";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close(); 
            }
        }
            
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginForm x = new LoginForm();
        x.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            if(jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("CSE")){
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='CSE' and course.course_year='1'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
            else if( jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("CSE")){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='CSE' and course.course_year='2'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
        }
            
            else if(jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("CSE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='CSE' and course.course_year='3'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
            else if(jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("CSE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='CSE' and course.course_year='4'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
             else if(jComboBox5.getSelectedItem().equals("1") && jComboBox4.getSelectedItem().equals("ECE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='ECE' and course.course_year='1'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
            else if(jComboBox5.getSelectedItem().equals("2") && jComboBox4.getSelectedItem().equals("ECE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='ECE' and course.course_year='2'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
            else if(jComboBox5.getSelectedItem().equals("3") && jComboBox4.getSelectedItem().equals("ECE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='ECE' and course.course_year='3'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
            else if(jComboBox5.getSelectedItem().equals("4") && jComboBox4.getSelectedItem().equals("ECE")){
                  Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from course,teacher where course.course_id = teacher.course_id and teacher.dept_name='ECE' and course.course_year='4'";
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               //data importing to table
               String Course_Id = rs.getString("course_id");
               String Course_Name = rs.getString("course_name");
               String Faculty_Name = rs.getString("t_name"); 
               String tbdata[] ={Course_Id,Course_Name,Faculty_Name};
               DefaultTableModel y = (DefaultTableModel)jTable2.getModel();  
               
               y.addRow(tbdata);
                 
           }
            con.close();
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                  dispose();          
                  Student s = new Student();
                  s.setVisible(true);
                  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
